services:
  smartlock:
    build: .
    container_name: smartlock
    ports:
      - "5000:5000"
    volumes:
      - ./faces_db:/app/faces_db
      - ./captures:/app/captures
      - ./data:/app/data
      - ${HOME}/.insightface/models:/root/.insightface/models
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/host-ca-certificates.crt:ro
    restart: always
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/host-ca-certificates.crt
      AUTH_DB_PATH: /app/data/users.db
    networks:
      - smartlock_net

networks:
  smartlock_net:
    driver: bridge
